<a href="https://colab.research.google.com/github/JavZon/Pandas/blob/main/pandas_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from pandas import Series
import numpy as np

In [5]:
arr1=np.arange(0,100,13)
arr1

array([ 0, 13, 26, 39, 52, 65, 78, 91])

In [6]:
obj=Series(arr1)

In [7]:
obj

0     0
1    13
2    26
3    39
4    52
5    65
6    78
7    91
dtype: int64

In [8]:
models=['tiger','lion','zebra','bear','deer','wolf','monkey','falcon']
obj=Series(arr1, index=models)
obj

tiger      0
lion      13
zebra     26
bear      39
deer      52
wolf      65
monkey    78
falcon    91
dtype: int64

In [14]:
obj[['wolf','wolf']]

wolf    65
wolf    65
dtype: int64

In [15]:
dict1={'horse':56,
       'donkey':80,
       'goat':31,
       'cat':29,
       'dog':65}


In [19]:
obj2=Series(dict1)
obj2

horse     56
donkey    80
goat      31
cat       29
dog       65
dtype: int64

In [20]:
models=['dog','cat','donkey','rat','horse','goat','dolphin']
obj2=Series(dict1, index=models)

In [21]:
obj2

dog        65.0
cat        29.0
donkey     80.0
rat         NaN
horse      56.0
goat       31.0
dolphin     NaN
dtype: float64

In [26]:
obj2['horse']

56.0

In [32]:
obj2[(obj2.index=='horse')|(obj2.index=='cat')]


cat      29.0
horse    56.0
dtype: float64

In [35]:
mask=(obj2.index=='horse')|(obj2.index=='cat')
mask

array([False,  True, False, False,  True, False, False])

In [36]:
obj2[mask]

cat      29.0
horse    56.0
dtype: float64

In [37]:
obj2[obj2<35]

cat     29.0
goat    31.0
dtype: float64

In [38]:
import numpy as np
data=Series([1,2,None,3,4,np.nan])
print(data.isnull())

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool


In [3]:
data2=Series([24,42,51,87,33], index=['Dog','Horse','Cat','Mouse','Goat'])
data2

Dog      24
Horse    42
Cat      51
Mouse    87
Goat     33
dtype: int64

In [4]:
data2.name="Zoo"
data2

Dog      24
Horse    42
Cat      51
Mouse    87
Goat     33
Name: Zoo, dtype: int64

In [9]:
data2.index.name='Animals'
data2.notnull()

Animals
Dog      True
Horse    True
Cat      True
Mouse    True
Goat     True
Name: Zoo, dtype: bool

In [6]:
data2.mean()

47.4

In [10]:
objj=Series([1,4,6,np.nan, 90])
objj

0     1.0
1     4.0
2     6.0
3     NaN
4    90.0
dtype: float64

In [12]:
objj.hasnans

True

In [15]:
from pandas import Series
ojj=Series([1,4,6,90])
ojj.hasnans

False

In [4]:
ojj.dtype

dtype('int64')

In [6]:
ojj.shape

(4,)

In [16]:
data=Series([10,20,30,40,50,60,70,80])
data.unique()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [17]:
abc=data.unique()
data.is_unique

True

In [18]:
data.hasnans

False

In [12]:
data[3]

40

In [19]:
data.head(3)

0    10
1    20
2    30
dtype: int64

In [20]:
data.tail(3)

5    60
6    70
7    80
dtype: int64

In [21]:
len(data)

8

In [22]:
data

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [26]:
data-9

0     1
1    11
2    21
3    31
4    41
5    51
6    61
7    71
dtype: int64

In [30]:
data.median()

45.0

In [31]:
data.max()

80

In [33]:
data.sum()

360

In [2]:
import pandas as pd

data = [40, 20, 60, 80, 50]
series = pd.Series(data, index=['A', 'B', 'C', 'D', 'E'])

# Sorting the Series by values in ascending order
sorted_by_values = series.sort_values()
print(sorted_by_values)

B    20
A    40
E    50
C    60
D    80
dtype: int64


In [4]:
data=pd.Series([20,10,35,0,1], index=['w','c','f','e','a'])
data.sort_index()

a     1
c    10
e     0
f    35
w    20
dtype: int64