<a href="https://colab.research.google.com/github/JavZon/Pandas/blob/main/Pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr1={'Bobur':25, "Sarvar":30, "Babakul": 41}
arr2=[1,3,5,6,92]
np.savez("mamulya",alhilal=arr1, alnasr=arr2)

In [ ]:
al_array=np.load('mamulya.npz')

In [ ]:
print(al_array)

In [ ]:
import pickle

In [ ]:
arr1=np.array(['Java','Lava','Gava','Mava','Zava','Pava'])
arr2=np.array([36,73,13,5,25,80])


In [ ]:
arr2

array([36, 73, 13,  5, 25, 80])

In [ ]:
mask=(arr1=='Java')|(arr1=='Mava')
mask

array([ True, False, False,  True, False, False])

In [ ]:
arr2

array([36, 73, 13,  5, 25, 80])

In [ ]:
arr2[mask]

array([36,  5])

In [ ]:
import pandas as pd
from pandas import Series

In [ ]:
obj=Series([3,86,14,26,95], index=['Football','Tennis','Swimming','Basketball','PS5'])

type(obj)

pandas.core.series.Series

In [ ]:
obj

Football       3
Tennis        86
Swimming      14
Basketball    26
PS5           95
dtype: int64

In [ ]:
obj['PS5']

95

In [ ]:
obj2=Series([4,27,31,88,100])


In [ ]:
obj2.values

array([  4,  27,  31,  88, 100])

In [ ]:
obj2.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
obj2

0      4
1     27
2     31
3     88
4    100
dtype: int64

In [ ]:
obj.index

Index(['Football', 'Tennis', 'Swimming', 'Basketball', 'PS5'], dtype='object')

In [ ]:
obj2[1]

27

In [ ]:
obj2[0]=32
obj2

0     32
1     27
2     31
3     88
4    100
dtype: int64

In [ ]:
data1=['Anvar','Jibawi','Eric','Haydar']
index1=['a','b','c','d']
obj3=Series(data=data1, index=index1)


In [ ]:
obj3

a     Anvar
b    Jibawi
c      Eric
d    Haydar
dtype: object

In [ ]:
obj3[obj3=='Haydar']

d    Haydar
dtype: object

In [ ]:
import numpy as np
np.(obj2)

0     5.656854
1     5.196152
2     5.567764
3     9.380832
4    10.000000
dtype: float64

In [ ]:
obj

Football       3
Tennis        86
Swimming      14
Basketball    26
PS5           95
dtype: int64

In [ ]:
obj2

0     32
1     27
2     31
3     88
4    100
dtype: int64

In [ ]:
np.power(obj,obj2)

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
Basketball   NaN
Football     NaN
PS5          NaN
Swimming     NaN
Tennis       NaN
dtype: float64

In [ ]:
type(obj.values)

numpy.ndarray

In [ ]:
np.square(obj2)

0     1024
1      729
2      961
3     7744
4    10000
dtype: int64

In [ ]:
np.isnan(obj2)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
obj2

0     32
1     27
2     31
3     88
4    100
dtype: int64

In [ ]:
obj2[3]=np.nan
obj2

0     32.0
1     27.0
2     31.0
3      NaN
4    100.0
dtype: float64

In [ ]:
np.isnan(obj2)

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [ ]:
dict1={'apple':30,'lemon':25,'orange':88,'banana':46,'dates':32}

In [ ]:
obj4=Series(dict1)
obj4

apple     30
lemon     25
orange    88
banana    46
dates     32
dtype: int64

In [ ]:
'banana' in obj4

True

In [ ]:
obj=Series([6,4,7,5], index=['a','b','c','d'])


In [ ]:
obj=Series([6,4,7,5], index=['a','c','d','f'])


In [ ]:
obj

a    6
c    4
d    7
f    5
dtype: int64

In [ ]:
dict1={'apple':30,'lemon':25,'orange':88,'banana':46,'dates':32}

In [ ]:
index2=['a','hazelnut','dates','eggs','orange','waterlemon','lemon','apple','banana']
obj=Series(dict1, index=index2)
obj

a              NaN
hazelnut       NaN
dates         32.0
eggs           NaN
orange        88.0
waterlemon     NaN
lemon         25.0
apple         30.0
banana        46.0
dtype: float64